apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: medlemskap-joark-listener
  namespace: medlemskap
  labels:
    team: medlemskap
spec:
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  image: {{image}}
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  ingresses:
    - https://medlemskap-joark-listener.intern.dev.nav.no
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      rules:
        - application: medlemskap-oppslag-pdfgen
        - application: logging
          namespace: nais-system
      external:
        - host: api-gw-q1.oera.no
        - host: api-gw-q2.oera.no
        - host: saf.dev-fss-pub.nais.io
        - host: login.microsoftonline.com
        - host: dokarkiv.dev-fss-pub.nais.io
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  env:
    - name: PDF_GEN_BASE_URL
      value: http://medlemskap-oppslag-pdfgen.medlemskap.svc.cluster.local
    - name: AZURE_TENANT
      value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
    - name: AZURE_AUTHORITY_ENDPOINT
      value: https://login.microsoftonline.com
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://api-gw-q1.oera.no/sts/SecurityTokenServiceProvider/
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://api-gw-q1.oera.no/security-token-service
    - name : JOARK_CLIENT_ID
      value: dev-fss.teamdokumenthandtering.dokarkiv-q1
    - name: JOARK_BASE_URL
      value: https://dokarkiv.dev-fss-pub.nais.io
    - name: PERSISTENCE_ENABLED
      value: Ja